name: Deploy to GCP
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: rstudio/r-base:4.3.0-focal
    steps:
      - name: Install SSL
        run: |
          sudo apt update
          sudo apt install libssl-dev

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Activate renv
        uses: r-lib/actions/setup-renv@v2


  deploy:
    needs: tests
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_APP_NAME: ${{ secrets.GCP_APP_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker auth
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Docker image
        run: |
          gcloud run deploy ${{ env.GCP_APP_NAME }} \
          --image ${{ env.IMAGE_NAME }} \
          --region europe-west3 \
          --platform managed \
          --port=3838 \
          --allow-unauthenticated